!include("varlist_lighting.scr")

VarVec3( "v_pp_shading_sun_color", [0, 0, 0] )
VarVec3( "v_pp_shading_sun_color_clouds_fade", [0, 0, 0] )
VarVec3( "v_pp_shading_sun_color_only", [0, 0, 0] )
VarVec3( "v_pp_shading_sun_color_clouds_off", [0, 0, 0] )
VarVec3( "v_pp_shading_sun_color_clouds_fade_only", [0, 0, 0] )
VarVec3( "v_pp_derived_sun_color", [0, 0, 0] ) //obsolete - remove
VarFloat("f_pp_lightning_on", 0.0)

